name: 游 Sugest칚o de t칩pico
description: Sugira um novo t칩pico para ser adicionado ao livro ou conte칰do que pode ser melhorado.
labels: [melhoria]
body:
  - type: markdown
    attributes:
      value: |
        Antes de sugerir uma nova melhoria, certifique-se de que essa sugest칚o j치 n칚o foi feita. Caso encontre uma sugest칚o similar, voc칡 pode contribuir para a discuss칚o, se necess치rio.
  - type: textarea
    id: description
    attributes:
      label: Descri칞칚o
      placeholder: |
        Eu gostaria de ver um artigo sobre...
        Eu acho que o artigo pode ser melhorado se...
        Encontrei novos materiais sobre...
        Podemos adicionar esse exerc칤cio...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Materiais e exemplos
      description: Links, exerc칤cios, exemplos de c칩digo, qualquer coisa que nos ajude a escrever um artigo sobre aquele assunto
      placeholder: |
        Tem um artigo legal sobre isso em...
        Encontrei esse exerc칤cio que pode ser adicionado...
